# Generated by Django 3.0.8 on 2020-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('tags', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
