# Generated by Django 3.0.8 on 2020-12-28 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='user_id',
            field=models.CharField(default=datetime.datetime(2020, 12, 28, 14, 39, 19, 721154, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
