# Generated by Django 3.0.8 on 2020-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201228_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
