# Generated by Django 3.0.8 on 2020-12-29 11:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 11, 15, 57, 83253, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
