# Generated by Django 3.0.8 on 2020-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201229_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user_id',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user_id',
            field=models.IntegerField(max_length=60),
        ),
    ]
