# Generated by Django 3.0.8 on 2020-12-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20201229_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='count_view',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
